on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: connectivity test
    steps:
      - uses: actions/checkout@v4
      - id: connectivity
        uses: tiggus/github-actions/connectivity@main
        with:
          who-to-greet: 'connectivity test'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foconnectivity.outputs.random-number }}
